/**
 * NEXORA FAQ Module
 */
(function() {
  'use strict';

  const FAQ_DATA = [
    {
      question: 'HOW DOES NEXORA PERSONALIZE A JOURNEY?',
      answer: 'NEXORA analyzes your destination, duration, budget, interests, travel style, and transport preference to score and rank all available activities and routes. Each recommendation is weighted by interest overlap, cost efficiency, and route optimization — resulting in an itinerary specifically tailored to your profile. This prototype uses a deterministic demo algorithm to simulate this process.',
    },
    {
      question: 'HOW DOES THE BUDGET OPTIMIZATION WORK?',
      answer: 'NEXORA allocates your budget across transport, accommodation, activities, food, and a safety buffer. The optimizer identifies where cost can be reduced — such as replacing higher-cost paid activities with free or low-cost alternatives nearby — without reducing your overall experience quality. Budget distribution adjusts dynamically when you change your total budget.',
    },
    {
      question: 'CAN I CHANGE MY TRIP AFTER GENERATING IT?',
      answer: 'Yes. The What-If Optimizer lets you change your budget, duration, travel style, and interest priorities at any time. NEXORA will instantly reoptimize your entire journey, showing you a before/after comparison and explaining what changed and why. Your journey is never fixed.',
    },
    {
      question: 'WHAT HAPPENS IF MY PLANS CHANGE?',
      answer: 'NEXORA includes a Disruption Adaptation engine. When a disruption is detected — such as weather changes, transport delays, or unexpected closures — NEXORA identifies affected activities, finds suitable alternatives, and rebuilds your itinerary while preserving your budget and key timeframes wherever possible.',
    },
    {
      question: 'DOES NEXORA USE LIVE DATA?',
      answer: 'This is a prototype demonstration. All journey data, cost estimates, optimization metrics, and recommendations are generated by a simulated AI demo algorithm using representative values for the Coimbatore → Ooty route. In a production system, NEXORA would connect to live transport APIs, accommodation providers, activity databases, and weather services for real-time planning.',
    },
  ];

  function renderFAQ() {
    const container = document.getElementById('faq-list');
    if (!container) return;

    container.innerHTML = FAQ_DATA.map((item, i) => `
      <div class="faq-item" id="faq-item-${i}">
        <button class="faq-question" aria-expanded="false" aria-controls="faq-answer-${i}" id="faq-btn-${i}">
          ${item.question}
          <span class="faq-chevron" aria-hidden="true">▾</span>
        </button>
        <div class="faq-answer" id="faq-answer-${i}" role="region" aria-labelledby="faq-btn-${i}">
          ${item.answer}
        </div>
      </div>
    `).join('');

    // Bind toggles
    container.querySelectorAll('.faq-question').forEach(btn => {
      btn.addEventListener('click', () => {
        const item   = btn.closest('.faq-item');
        const isOpen = item.classList.toggle('open');
        btn.setAttribute('aria-expanded', String(isOpen));
      });
    });
  }

  document.addEventListener('DOMContentLoaded', renderFAQ);

})();
